### PR TITLE
Multiple Fixes

### PR DESCRIPTION
**Pull request by acornforth**
- Add option to use Province abbreviation instead of code for US state fields
- Allow override of money conversion for sylius installations storing amounts with different precision.
- fix translations typos (also covers #11 )
- tidy up some code smells
- add ecs.php cofing file
- fix some composer.json issues preventing install on newer php and sylius

### CODE REVIEW

**Comment by sbarbat** [comment]
Hey @acornforth, thank you very much for your contribution 🎉 . Seems there are some merge conflicts with the last change we merged. Can you fix them to merge this?

Thanks

**Comment by acornforth** [comment]
Happy to, give me a moment :+1:

**Comment by acornforth** [comment]
good to go

**Comment by euperia** [comment]
@sbarbat are there any plans to merge this PR?  It will fix an issue I'm having with BillingState values and non-us addresses.

**Comment by sbarbat** [comment]
It seems its formatting a lot of files that shouldn't, if you can solve it then would be merged 😄  @euperia

**Comment by acornforth** [comment]
@sbarbat that is my bad for not limiting the scope of my PR to a single feature. I wanted to make that fix, but as i was working on the code i realized that there were a number of inconsitencies in the code style. To help keep code from all contributors  consistent, i added a config file for Easy Coding Standard (already a dependency in sylius) with a basic rule-set, and applied all the suggested fixes.

Obviously as the maintainer it's up to you if you want to accept those changes, but i thought they were beneficial.

@euperia If you want to take advantage of these changes you could always use my forked repo ( i suggest you make your own fork) you can then configure composer to pull the package from your fork instead of this repo.

**Comment by sbarbat** [comment]
@acornforth sorry it's been some time since I last developed with PHP so didn't remember about those standards. 

If all the stylings are done using ECS, lets make sure we use that styling in future PR's.

Approving 😄 

@acornforth thank you 🎉 
@euperia thanks for the follow-up 🙏

**Pull request merged**
